name: face
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  json_annotation: ^3.0.0
  provider: 4.3.2+3
  retrofit: 1.3.4+1
  dio: 3.0.10
  hive: 1.4.4+1
  hive_flutter: 0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  retrofit_generator: 1.4.1+1

flutter:
  uses-material-design: true

scripts:
  generate: fvm flutter pub run build_runner build --delete-conflicting-outputs
